name: Greeting
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greet New Contributors
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! I see you've opened your first issue here, thank you! You're helping the development of NexSuite substantially!" # optional
        pr-message: "Hey! I see you've opened your first PR here, thank you! You're helping the development of NexSuite by adding your own wisdom to it!" # optional

